### ISSUE TITLE
yo the site is super empty

### ISSUE THREAD

**Issue by sabeegrewal** [sabeegrewal/bills-sonoma#4]
- [x] add email 
- [x] add shows
- [x] add bio
- [x] add low key controls for pigeon boi
- [x] add favicon
- [x] add sitemap.xml
- [x] register on google console n shi 

What else? Any ideas? cc @dpgil

**Comment by dpgil** [comment]
Added favicon with pr #5

**Comment by sabeegrewal** [comment]
added sitemap and email :~) going to close
